apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../base

namespace: development

labels:
  - pairs:
      environment: development

patches:
  - target:
      kind: Deployment
      name: indexify
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: pdf-parser
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

configMapGenerator:
  - name: indexify-config
    behavior: merge
    literals:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug

