apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config/configmap.yaml
  - elasticsearch/elasticsearch-deployment.yaml
  - elasticsearch/elasticsearch-service.yaml
  - executors/pdf-parser-deployment.yaml
  - indexify/indexify-deployment.yaml
  - indexify/indexify-service.yaml
  - storage/persistent-volume-claims.yaml
  - storage/storage-class.yaml
