# k8s/base/storage/persistent-volume-claims.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: indexify-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azure-disk-standard
  resources:
    requests:
      storage: 50Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azure-disk-standard
  resources:
    requests:
      storage: 50Gi
